sudo: required
language: node_js
dist: trusty

services:
  docker

script:
  - docker build .
deploy:
  provider: npm
  email: rzr@users.sf.net
  api_key:
    secure: "M2oR4nM1wt5vub2FneNoQrhLaLF/y/40TYW172g/5MfpQYwItj/Y9cG1ZtzujVwMJxcwNf1KEMhpVsNvcxebxgjcgnjGr0KiQ4cYtdzLqx6VafI/iQBhuDXVMxeLAsIiMxPNv1iVnye90v5cGzIl6pxQUqVL8CSjTBmSZ/6QIEmuCOpd5R0aATYO73CymL55Gcf4i6qQDKvsu7B+GWe8Q1YnKA6Ch4IisBaMn8vA1OQB0ILC1qBHMMwA0JN90BO2pw5oqclVBFgKcESbtvjlZ6CfXCKvGbyMNvfaBP8gD4Z9eBpYv6ezaXGc/N3E5jPvoAhqJxXLm7DGd9/xq2nJGrg9/B60Fy72/yDQ+Ip6KgV6cj/Fu5wo9qU7982+ElH5X2BjQi2Xu9H7FAnd9hlmFdFVTrAlpxjNz58vYHKeYILhL63VgxXN59i+tUD+xFI0olZZxd9WB04Jh5mVLuMbkHSklZlM33TYe73BGkl3NQKRRcrpuOInVwLKr6rABF9jHfymSdnWK3vBhMiy48O4EYTOSKvnXlqPeHV17K0vBiw7kSPNx6ewLEO3ivbsxl/S9Sr1t99avoVw8xO1yAx37uIrNwieeyrkO63EXHM0hE0ybqg1X/Xpnef60dEplHGsaw4ZyCemyQ2byRTiry0CqKJTjgZRNmB2wDE1B31bxh8="
  on:
    tags: true
    repo: rzr/webthing-iotjs
